version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./chroma_store:/app/app/chroma_store
    env_file:
      - .env
